chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'


urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/add-user/', views.add_user, name='add_user'),
    path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user_detail'),
    path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit_user'),
    path('chat-admin/<str:uuid>/', views.room, name='room'),
    path('chat-admin/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

jatte/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

chat/models.py
from django.db import models

from account.models import User


class Message(models.Model):
    body = models.TextField()
    sent_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('created_at',)
    
    def __str__(self):
        return f'{self.sent_by}'


class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    CHOICES_STATUS = (
        (WAITING, 'Waiting'),
        (ACTIVE, 'Active'),
        (CLOSED, 'Closed'),
    )


    uuid = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    agent = models.ForeignKey(User, related_name='rooms', blank=True, null=True, on_delete=models.SET_NULL)
    messages = models.ManyToManyField(Message, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)
    case = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)
    q1 = models.CharField(max_length=255, blank=True, null=True)
    q2 = models.CharField(max_length=255, blank=True, null=True)
    q3 = models.CharField(max_length=255, blank=True, null=True)
    q4 = models.CharField(max_length=255, blank=True, null=True)
    q5 = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return f'{self.client} - {self.uuid}'

chat/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from account.forms import AddUserForm, EditUserForm
from account.models import User

from .models import Room


@require_POST
def create_room(request, uuid):
    name = request.POST.get('name', '')
    url = request.POST.get('url', '')
    q1 = request.POST.get('1stQ')
    q2 = request.POST.get('2ndQ')
    q3 = request.POST.get('3rdQ')
    q4 = request.POST.get('4thQ')
    q5 = request.POST.get('5thQ')
    print("Created Chat room!")

    Room.objects.create(uuid=uuid, client=name, url=url, q1 = q1, q2 = q2, q3 = q3, q4 = q4, q5 = q5)

    return JsonResponse({'message': 'room created'})


@login_required
def admin(request):
    rooms = Room.objects.all()
    users = User.objects.filter(is_staff=True)

    return render(request, 'chat/admin.html', {
        'rooms': rooms,
        'users': users
    })


@login_required
def room(request, uuid):
    room = Room.objects.get(uuid=uuid)

    if room.status == Room.WAITING:
        room.status = Room.ACTIVE
        room.agent = request.user
        room.save()

    return render(request, 'chat/room.html', {
        'room': room
    })


@login_required
def delete_room(request, uuid):
    if request.user.has_perm('room.delete_room'):
        room = Room.objects.get(uuid=uuid)
        room.delete()
                
        messages.success(request, 'The room was deleted!')

        return redirect('/chat-admin/')
    else:
        messages.error(request, 'You don\'t have access to delete rooms!')

        return redirect('/chat-admin/')


@login_required
def user_detail(request, uuid):
    user = User.objects.get(pk=uuid)
    rooms = user.rooms.all()

    return render(request, 'chat/user_detail.html', {
        'user': user,
        'rooms': rooms
    })


@login_required
def edit_user(request, uuid):
    if request.user.has_perm('user.edit_user'):
        user = User.objects.get(pk=uuid)

        if request.method == 'POST':
            form = EditUserForm(request.POST, instance=user)

            if form.is_valid():
                form.save()
                
                messages.success(request, 'The changes was saved!')

                return redirect('/chat-admin/')
        else:
            form = EditUserForm(instance=user)

        return render(request, 'chat/edit_user.html', {
            'user': user,
            'form': form
        })
    else:
        messages.error(request, 'You don\'t have access to edit users!')

        return redirect('/chat-admin/')


@login_required
def add_user(request):
    if request.user.has_perm('user.add_user'):
        if request.method == 'POST':
            form = AddUserForm(request.POST)

            if form.is_valid():
                user = form.save(commit=False)
                user.is_staff = True
                user.set_password(request.POST.get('password'))
                user.save()

                if user.role == User.MANAGER: 
                    group = Group.objects.get(name='Managers')
                    group.user_set.add(user)
                
                messages.success(request, 'The user was added!')

                return redirect('/chat-admin/')
        else:
            form = AddUserForm()

        return render(request, 'chat/add_user.html', {
            'form': form
        })
    else:
        messages.error(request, 'You don\'t have access to add users!')

        return redirect('/chat-admin/')

chat/templates/chat/partials/chat_bubble.html
<style>
    .a{
        color:  #ff0078 !important; 
    }
    .a:hover{
        color: #ff0078 !important;
        text-decoration: none !important;
    }
    .top-bar {
      padding: 10px 0;
      text-align: right;
      /* background-color:  */
      /* background-color:linear-gradient(180deg, #f02d85, #FF6648); */
      border-radius: 10px;
    }
    .top-bar button {
      background: none;
      border: solid 1px #EB0000;
      border-radius: 20px;
      padding: 5px 15px;
      margin: 0 5px;
      color: #EB0000;
    }
    .chat-area {
      width: 40%;
      padding: 20px;
      height: calc(100vh - 120px);
      overflow-y: auto;
    }
    .chat-area-ans {
      width: 40%;
      padding: 20px;
      height: calc(100vh - 120px);
      overflow-y: auto;
    }
    .chat-bubble {
      background-color: #f8f8f8;
      border-radius: 20px;
      padding: 15px;
      margin-bottom: 10px;
      display: inline-block;
    }
    .chat-input {
      position: fixed;
      bottom: 0;
      left: 0;
      width: 100%;
      padding: 10px;
      background-color: #fff;
      border-top: solid 1px #ddd;
    }
    .response-button-back {
      background-color: transparent;
      border: solid 1px  #007bff;
      border-radius: 20px;
      padding: 10px 20px;
      font-size: 16px;
      color: #007bff;
      margin: 5px;
    }
    .response-button {
      background-color: #007bff;
      border: none;
      border-radius: 20px;
      padding: 10px 20px;
      font-size: 16px;
      color: white;
      margin: 5px;
    }
    .progress-bar{
        background-color:#F02D84;
    }
  </style>

<div id="chat">
    <div id="chat_icon">
        <img src="/static/images/Login/Logo.png" alt="Globe Icon" style="margin-left:40%; max-width: 250px;">
        <h2 >How can I help you today?</h2>
        <button id="chat_open" style="margin:auto; width: 450px; height: 100px;" class="chat-button flex items-center">
           <h3 style="align-content: center; margin: auto;">Start Chat</h3>             
        </button>
    </div>
    
    <div id="chat_welcome" class="hidden">
        <div id="first_phase">
            <div class="top-bar" style="background-color: linear-gradient(to right, #F02D84, #FF6648);">
                <button id="chat_join" style=" background-color: #F02D84;color: white;" class="skip-button" type="button">Skip Questionnaire</button>
                <button type="button">
                    <a style="color: #EB0000; text-decoration: none;" href="{% url 'core:index' %}" >Create New</a>
                </button>
                <button type="button">Share</button>
                <br>
                <br>
                <div style="padding: 10px;">
                    <div class="progress" style="height: 40px; border-radius: 25px;" >
                        <div class="progress-bar progress-bar-striped" id="progress" role="progressbar" aria-label="Default striped example" style="width: 20%;font-size: medium;" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"> Answer 1 of 5</div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div>
                    <img src="/static/images/Login/Logo.png" style="width: 40px; height: 40px; margin: 20px; margin-top: 30px;">
                </div>
                <div class="chat-area">
                    <!-- Chat messages here -->
                    <div id="First_question">
                        <div class="chat-bubble">
                            Hi! I'm AirMed's messaging assistant. Before connecting you with a remote doctor, let's gather some information to help the remote doctor get a better understanding of the situation.
                        </div>
                        <div class="chat-bubble">
                            Is the patient still conscious?
                        </div>
                        <div class="option-chat-bubble">
                            <div>
                                <button type="button" id="first_ans_Yes" class="response-button">Yes</button>
                                <button type="button" id="first_ans_No" class="response-button">No</button>
                                <button type="button" id="first_ans_NS" class="response-button">Not Sure</button>
                            </div>
                        </div>
                        <div class="answer-chat-bubble hidden">
                            <div class="Yes">
                                <button type="button" class="response-button">Yes</button>
                            </div>
                            <div class="No">
                                <button type="button" class="response-button">No</button>
                            </div>
                            <div class="Not Sure">
                                <button type="button" class="response-button">Not Sure</button>
                            </div>
                        </div>
                    </div>
                    <div id="Second_question" class="hidden">
                        <div class="chat-bubble">
                            Is the patient experiencing any discomfort, pressure, or pain in their chest?
                        </div>
                        <div class="answer-chat-bubble">
                            <div>
                                <button type="button" id="sec_ans_back" class="response-button-back">Back</button>
                                <button type="button" id="sec_ans_Yes" class="response-button">Yes</button>
                                <button type="button" id="sec_ans_No" class="response-button">No</button>
                                <button type="button" id="sec_ans_NS" class="response-button">Not Sure</button>
                            </div>
                        </div>
                    </div>
                    <div id="Third_question" class="hidden">
                        <div class="chat-bubble">
                            Is the patient having difficulty breathing or experiencing shortness of breath? 
                        </div>
                        <div class="answer-chat-bubble">
                            <div>
                                <button type="button" id="third_ans_back" class="response-button-back">Back</button>
                                <button type="button" id="third_ans_Yes" class="response-button">Yes</button>
                                <button type="button" id="third_ans_No" class="response-button">No</button>
                                <button type="button" id="third_ans_NS" class="response-button">Not Sure</button>
                            </div>
                        </div>
                    </div>
                    <div id="Fourth_question" class="hidden">
                        <div class="chat-bubble">
                            Is the patient nauseous or feeling lightheaded?
                        </div>
                        <div class="answer-chat-bubble">
                            <div>
                                <button type="button" id="fourth_ans_back" class="response-button-back">Back</button>
                                <button type="button" id="fourth_ans_Yes" class="response-button">Yes</button>
                                <button type="button" id="fourth_ans_No" class="response-button">No</button>
                                <button type="button" id="fourth_ans_NS" class="response-button">Not Sure</button>
                            </div>
                        </div>
                    </div>
                    <div id="Fifth_question" class="hidden">
                        <div class="chat-bubble">
                            Is the patient experiencing a seizure?
                        </div>
                        <div class="answer-chat-bubble">
                            <div>
                                <button type="button" id="fifth_ans_back" class="response-button-back">Back</button>
                                <button type="button" id="fifth_ans_Yes" class="response-button">Yes</button>
                                <button type="button" id="fifth_ans_No" class="response-button">No</button>
                                <button type="button" id="fifth_ans_NS" class="response-button">Not Sure</button>
                            </div>
                            <input type="text" name="name" id="chat_name" class="w-full mb-4 py-2 px-6 rounded-xl bg-gray-100" placeholder="Enter name (Optional)">
                        </div>
                    </div>
                    <!-- Add more chat bubbles as needed -->
                </div>
            </div>
            <!-- <button id="chat_join" class="py-2 px-6 rounded-xl text-white bg-rose-600">Tap Here to talk to a doctor immediately</button> 
            <input type="text" name="name" id="chat_name" class="w-full mb-4 py-2 px-6 rounded-xl bg-gray-100" placeholder="Your name..."> -->
            <script src="https://kit.fontawesome.com/your-fontawesome-kit.js"></script>
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.9/dist/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        </div>
    </div>

    <!-- <div id="chat_welcome" class="hidden">
        <input type="text" name="name" id="chat_name" class="w-full mb-4 py-2 px-6 rounded-xl bg-gray-100" placeholder="Your name...">

        <button id="chat_join" class="py-2 px-6 rounded-xl text-white bg-rose-600">Join chat</button>
    </div> -->

    <div id="chat_room" style="background-color: white;" class="hidden">
        <div id="chat_log" class="mb-4 p-4 rounded-xl h-[500px] overflow-scroll">
            <p>Welcome to our chat! Please type your message and wait for an agent to join...</p>
        </div>

        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Type your message...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl">Send</button>
    </div>
</div>

chat/templates/chat/partials/chat_bubble_original.html
<div id="chat">
    <div id="chat_icon">
        <img src="/static/images/Login/Logo.png" alt="Globe Icon" style="margin-left:40%; max-width: 250px;">
        <h2 >How can I help you today?</h2>
        <button id="chat_open" style="margin:auto; width: 450px; height: 100px;" class="chat-button flex items-center">
           <h3 style="align-content: center; margin: auto;">Start Chat</h3>             
        </button>
    </div>
    
    <div id="chat_welcome" class="hidden">
        <input type="text" name="name" id="chat_name" class="w-full mb-4 py-2 px-6 rounded-xl bg-gray-100" placeholder="Your name...">

        <button id="chat_join" class="py-2 px-6 rounded-xl text-white bg-rose-600">Join chat</button>
    </div>

    <div id="chat_room" class="hidden">
        <div id="chat_log" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll">
            <p>Welcome to our chat! Please type your message and wait for an agent to join...</p>
        </div>

        <input type="text" name="body" id="chat_message_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Type your message...">
        <button id="chat_message_submit" class="py-2 px-6 bg-rose-600 text-white rounded-xl">Send</button>
    </div>
</div>

chat/templates/chat/partials/room_list.html
<div class="grid grid-cols-4 gap-4">
    {% for room in rooms %}
        <div class="p-4 rounded-xl {% if room.status == 'waiting' %}bg-emerald-100{% elif room.status == 'active' %}bg-yellow-100{% else %}bg-gray-100{% endif %}">
            <h3 class="mb-4 text-lg">{{ room.client }} </h3>

            <p>
                <!-- <b>ID: </b><br> -->
                
                <b>Status: </b>{{ room.get_status_display }}<br>
                <b>EMT: </b>{% firstof room.agent.name 'None yet...' %}<br>
                <b>Case:</b>{% firstof room.case 'Not available'%}<br>
                <b>ID: {{ room.uuid }}</b><br>
            </p>

            <a href="{% url 'chat:room' room.uuid %}" class="mt-4 inline-block py-2 px-6 bg-emerald-800 text-white rounded-xl">Join</a>

            <a href="{% url 'chat:delete_room' room.uuid %}" class="mt-4 inline-block py-2 px-6 bg-rose-800 text-white rounded-xl">Delete</a>
        </div>
    {% endfor %}
</div>